### ISSUE TITLE
unable to run app

### ISSUE THREAD

**Issue by jeeva-nikam** [FortechRomania/express-mongo-example-project#14]
ERROR - 
D:\Node-MongoDB\express-mongo-example-project-master3>npm start

> node-starter@1.0.0 start D:\Node-MongoDB\express-mongo-example-project-master3
> nodemon --watch src src/index.js

[nodemon] 1.17.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: D:\Node-MongoDB\express-mongo-example-project-master3\src/**/*
[nodemon] starting `node src/index.js`
2:07:56 PM - info: Info message
2:07:56 PM - warn: Warning message
2:07:56 PM - debug: Debugging info
D:\Node-MongoDB\express-mongo-example-project-master3\src\app\users\controller.js:5
exports.register = async ( req, res ) => {
                         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Node-MongoDB\express-mongo-example-project-master3\src\app\users\router.js:3:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by anamariaoros** [comment]
Hi @jeeva-nikam,
Can you tell me what version of node you use/have installed?
